apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rpef
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rpef
    app.kubernetes.io/part-of: tkrw-pr712-0075-0008-app
  name: devfile-sample-rpef
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rpef
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rpef
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0008-tenant/tkrw-pr712-0075-0008-app/devfile-sample-rpef@sha256:10b9454958bdec254c3d4501c42ca4238fc0f322ab8175fbd5e595a2401f1933
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
